# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Min-Hsien Weng
email: samminweng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
PhD in Computer Science | A skilled software engineering researcher with a growing interest in applying machine learning, particularly NLP and LLMs, to diverse challenges. | NZ resident

Main research interests span software verification, programming language, and compilers. My recent postdoc at Waikato University, New Zealand, ignited a strong interest in applying natural language processing (NLP) and large language models (LLMs) to understand complex urban environmental changes. This emerging focus complements my extensive industrial experience in hardware and software integration gained at ITRI, Taiwan, allowing me to bridge the gap between theoretical research and practical applications.

My CV: https://samminweng.github.io/Min-Hsien_Weng_CV.pdf
My GitHub repository: https://github.com/samminweng
Kaggle Notebook, Dataset and Discussion Expert (Top 300 of 55,700 participants): https://www.kaggle.com/minhsienweng

* Experience
1 year of teaching experience in computer science
3 years of natural language processing/machine learning experiences (PostDoc)
7 years of compiler and programming language research (PhD + Master at Waikato University)
9 years of RFID and PDM software development at ITRI (Taiwan)

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samminweng
github_username:  samminweng

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
